MS-190: Firebase implementation in backend
BaSD-2021/Dami-MindSet-server pull request #121
Opened 2021-12-27 03:46 UTC by sofpag

2021-12-27 13:36 UTC, julianv97 requested changes

2021-12-27 13:36 UTC, julianv97 commented on src/models/Users.js
> +const UsersSchema = new Schema({
User only needs this fields:

- email
- firebaseUid
- token

2021-12-27 13:36 UTC, julianv97 commented on src/routes/auth.js
> +const { register, login, logout } = controller;
login and logout are not created in the auth controller

2021-12-27 13:59 UTC, julianv97 requested changes
We need to add the authRouter in the index of routes

2021-12-28 13:20 UTC, damianalvarez requested changes

2021-12-28 13:20 UTC, damianalvarez commented on src/models/Users.js
> +  repeatpassword: {
@sofpag can you get rid of this? Given that we only need to do this validation on the frontend side

2021-12-29 14:49 UTC, julianv97 approved these changes

2021-12-29 14:49 UTC, merged