MS-57: Clients crud
BaSD-2021/Dami-MindSet-server pull request #71
Opened 2021-11-18 00:03 UTC by EugenioPonzone

2021-11-18 00:15 UTC, damianalvarez commented on public/js/clients.js
> +      <td><button class="button-list" onclick="updateClient(${client._id})"><img src="img/Icon-edit.png" alt="Edit"></button></td>
@EugenioPonzone Another approach instead of passing the IDs as params to the respective functions in order to keep the reference to each row, is adding a data attr (e.g. `data-id="${client._id}"`) and read the value inside the update or remove functions

2021-11-18 13:19 UTC, NicoMunoz909 requested changes

2021-11-18 13:19 UTC, NicoMunoz909 commented on public/clients.html
> +            <th></th>
There are two empty th tags here. We should remove them

2021-11-18 13:19 UTC, NicoMunoz909 commented on public/clients.html
> +              <fieldset>
this fieldset tag should be removed

2021-11-18 13:19 UTC, NicoMunoz909 commented on public/clients.html
> +              <fieldset>
this fieldset tag should be removed

2021-11-18 18:51 UTC, nicolasblasco commented on public/js/clients.js
> +      </form></td>`;
@EugenioPonzone we should only leave </td>`

2021-11-19 23:20 UTC, EugenioPonzone commented on public/js/clients.js
> +      <td><button class="button-list" onclick="updateClient(${client._id})"><img src="img/Icon-edit.png" alt="Edit"></button></td>
Finally, I could do it in a different way but I dont know if it is the best.  I don't really sure but I guess the problem was that js functions can't receive a so long parameter as ._id.

2021-11-20 00:36 UTC, BaltazarCortina commented on public/js/clients.js
> +  const url = "http://localhost:4000/api/clients/";
@EugenioPonzone since we're using this url for more than one request, we could define it outside of the function and call it directly

2021-11-20 00:36 UTC, BaltazarCortina commented on public/js/clients.js
> +  let dataBody = {
@EugenioPonzone shouldn't this be a const?

2021-11-20 00:36 UTC, BaltazarCortina commented on public/js/clients.js
> +      <td><button class="button-list" onclick="openDeleteModal(${i})"><img src="img/Icon-remove.png" alt="Remove"/></button></td>
@EugenioPonzone we shouldn't be mixing html with js, maybe we could add an event listener to those buttons in the same create function

2021-11-20 00:36 UTC, BaltazarCortina commented on public/js/clients.js
> +  validateActivity();
@EugenioPonzone are we validating the fields when we open the modal?

2021-11-20 00:36 UTC, BaltazarCortina commented on public/js/clients.js
> +  };
@EugenioPonzone this is exactly the same code as in update. Maybe we could make it a separate function and call it create and update, so we can reuse the code

2021-11-20 00:36 UTC, BaltazarCortina commented on public/js/clients.js
> +      </ul>`;
@EugenioPonzone the contents of this .then and the .catch are also repeated in the update function. These could be 'success' and 'fail' functions

2021-11-20 00:36 UTC, BaltazarCortina commented on public/js/clients.js
> +function  validateName(){
@EugenioPonzone the validation functions could be in a different file, most fields are the same in every resource we could reuse that code

2021-11-20 01:49 UTC, EugenioPonzone commented on public/clients.html
> +            <th>id</th>
Im not sure, it was in the basic html structure. Besides, I use it to catch it and added in the url as a param, because i couldnt send it as a parameter in a function.

2021-11-20 01:49 UTC, EugenioPonzone commented on public/clients.html
> +              </fieldset>
I use it to catch it and added in the url as a param.

2021-11-20 02:00 UTC, EugenioPonzone commented on public/js/clients.js
> +      <td><button class="button-list" onclick="openDeleteModal(${i})"><img src="img/Icon-remove.png" alt="Remove"/></button></td>
We are in the same page, but I have second thougths about this particular case because Im making the html with the js and I believe the reason for not mixing is to be able to control all the script in a js file.

2021-11-20 03:15 UTC, BaltazarCortina commented on public/clients.html
> +            <th>id</th>
I don't think it's something the user needs to see, but I get the point. Anyway, if the issue is storing it somewhere, maybe we could use an array for that. We fill the array with the ids when we request the info, and if we remove a client we remove that element of the array. That way the index in the array should match the position in the table. Just an idea though, the way it is now is working fine!

2021-11-20 03:16 UTC, BaltazarCortina commented on public/js/clients.js
> +      <td><button class="button-list" onclick="openDeleteModal(${i})"><img src="img/Icon-remove.png" alt="Remove"/></button></td>
That makes sense, maybe you're right about that

2021-11-20 13:35 UTC, EugenioPonzone commented on public/clients.html
> +            <th>id</th>
I have implemented your suggestions and I guess it still works correctly!

2021-11-20 13:38 UTC, EugenioPonzone commented on public/clients.html
> +              </fieldset>
At the end, I removed that field and replaced with a global let. That field could have been quite confusing.

2021-11-20 15:15 UTC, nicolasblasco commented on public/js/validationsClients.js
> +    return errorAddress.innerText = "Address cannot be bigger than 100 or smaller than 6.";
@EugenioPonzone we could validate if there is a space in the address. 
If we write Callao543 it validates it correctly, but should write it like this: Callao 543.

2021-11-20 20:34 UTC, EugenioPonzone commented on public/js/validationsClients.js
> +    return errorAddress.innerText = "Address cannot be bigger than 100 or smaller than 6.";
Solved

2021-11-20 20:35 UTC, EugenioPonzone commented on public/clients.html
> +              <fieldset>
Solved

2021-11-20 20:35 UTC, EugenioPonzone commented on public/clients.html
> +              <fieldset>
Solved

2021-11-22 14:52 UTC, damianalvarez approved these changes

2021-11-22 14:52 UTC, merged